name: Microservices CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

  docker_build:
    needs: build_and_test
    runs-on: ubuntu-latest
    name: Docker Build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Product Service Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./product-service
          push: false
          tags: product-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Order Service Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./order-service
          push: false
          tags: order-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max